import os
# Set PyTorch memory allocator to reduce fragmentation
os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'expandable_segments:True'

import argparse
from time import time
import cv2 as cv
import numpy as np
from PIL import Image
from matplotlib import pyplot as plt
# plt.switch_backend('agg')
# from skimage.measure import compare_psnr  # 用于计算两个图像之间的峰值信噪比
# from skimage.measure import compare_ssim  # 用于计算两个图像之间的结构相似性指数
import torch.backends.cudnn as cudnn
from PIL import Image
import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import transforms
from torch.utils.data import DataLoader
from torch.optim.lr_scheduler import StepLR, MultiStepLR
from torch.utils.data import DataLoader
from scipy.ndimage.filters import gaussian_filter
from scipy.signal import find_peaks
import torch.optim as optim
from error import *
from IntegrateNet_SegLogitsGuidance import *
from Netdataset import *


# system-related parameters
data_dir = "dataset"
train_list = "train.txt"
val_list = "val.txt"

# normalization
image_scale = 1. / 255
image_mean = [0.3751, 0.4294, 0.3128]  # 蓝莓图片计算均值
image_std = [1, 1, 1]  # image_std = [0.2396, 0.2476, 0.2199]蓝莓
image_mean = np.array(image_mean).reshape((1, 1, 3))
image_std = np.array(image_std).reshape((1, 1, 3))
crop_num = 4
input_size = 64
output_stride = 8

# model-related parameters
optimizer = 'sgd'
batch_size = 16
crop_size = (256,256)
learning_rate = 0.01
# milestones=[200,500]
momentum = 0.95
mult = 1
num_epoch = 300
weight_decay = 0.0005
mae_max = 10000


def save_checkpoint(state, snapshot_dir, filename='model_ckpt.pth.tar'):
    torch.save(state, '{}/{}'.format(snapshot_dir, filename))


# training part
def train(net, train_loader, optimizer, criterion, criterion2, epoch, lamda, seg_weight=0.0, bce_loss=None):
    net.train()  # set train module
    target_filter = torch.ones((1, 1, 64, 64), dtype=torch.float32, device='cuda')  # generate ground truth local count map
    running_loss = 0.0

    for i, sample in enumerate(train_loader):
        inputs, targets = sample['image'], sample['target']
        masks = sample.get('mask', None)
        length = len(inputs)  # equal to crop number
        for j in range(length):
            input,target = inputs[j],targets[j]
            input,target = input.cuda(), target.cuda()
            mask = None
            if masks is not None:
                mask = masks[j].cuda()

            optimizer.zero_grad()
            dic = net(input)
            density = dic['density']  # predicted density map
            local_count = dic['local_count']  # predicted local count map
            seg_logits = dic.get('segmentation', None)

            loss1 = criterion(density, target)
            target = F.conv2d(target, target_filter, stride=64)  # ground truth local count map generated by convolution with density map
            loss2 = criterion2(local_count, target)
            loss = (1-lamda)*loss1+lamda*loss2
            if seg_weight > 0 and (seg_logits is not None) and (mask is not None) and (bce_loss is not None):
                # downsample mask to match seg_logits if needed
                if seg_logits.size()[-2:] != mask.size()[-2:]:
                    mask_ds = F.interpolate(mask, size=seg_logits.size()[-2:], mode='nearest')
                else:
                    mask_ds = mask
                loss_seg = bce_loss(seg_logits, mask_ds)
                loss = loss + seg_weight * loss_seg

            loss.backward()
            optimizer.step()
            running_loss += loss.item()

    if epoch > 900:
        print('epoch: %d, train: %d/%d, ''loss: %.5f' % (epoch, i + 1, len(train_loader),running_loss / (i + 1)))
    net.train_loss['epoch_loss'].append(running_loss / (length*(i + 1)))  # record training loss
    torch.cuda.empty_cache()


# testing part
def validate(net, val_loader, epoch,criterion,criterion2,lamda, seg_weight=0.0, bce_loss=None, eval_with_mask=False):
    # set evaluation module
    net.eval()

    target_filter = torch.ones((1, 1, 64, 64), dtype=torch.float32, device='cuda')
    iou_list = []
    dice_list = []
    running_loss = 0.0
    # 改为收集所有地块的预测值和真实值
    all_pd_counts = []
    all_gt_counts = []
    with torch.no_grad():
        for i, sample in enumerate(val_loader):
            image, target = sample['image'], sample['target']
            mask = sample.get('mask', None)
            pts = sample.get('points', None)
            input = image.cuda()
            target = target.cuda()

            # Check if image is too large for single forward pass
            _, _, h, w = input.shape
            max_size = 3200  # max dimension before sliding window
            if h > max_size or w > max_size:
                # Sliding window inference for large images
                stride = 512
                crop_size = 768
                output_full = torch.zeros((1, 1, h, w), device='cuda')
                seg_logits_full = torch.zeros((1, 1, h, w), device='cuda') if seg_weight > 0 else None
                count_map = torch.zeros((1, 1, h, w), device='cuda')
                
                for y in range(0, h, stride):
                    for x in range(0, w, stride):
                        y_end = min(y + crop_size, h)
                        x_end = min(x + crop_size, w)
                        y_start = max(0, y_end - crop_size)
                        x_start = max(0, x_end - crop_size)
                        
                        patch = input[:, :, y_start:y_end, x_start:x_end]
                        dic_patch = net(patch)
                        out_patch = dic_patch['density']
                        seg_patch = dic_patch.get('segmentation', None)
                        
                        output_full[:, :, y_start:y_end, x_start:x_end] += out_patch
                        if seg_logits_full is not None and seg_patch is not None:
                            seg_logits_full[:, :, y_start:y_end, x_start:x_end] += seg_patch
                        count_map[:, :, y_start:y_end, x_start:x_end] += 1.0
                
                output = output_full / count_map.clamp(min=1.0)
                seg_logits = seg_logits_full / count_map.clamp(min=1.0) if seg_logits_full is not None else None
                local_count = None  # local count not meaningful in sliding window mode
            else:
                # Normal single forward pass for small images
                dic = net(input)
                output = dic['density']
                local_count = dic['local_count']
                seg_logits = dic.get('segmentation', None)

            loss1 = criterion(output, target)
            if local_count is not None:
                d = F.conv2d(target, target_filter, stride=64) # ground truth local count map
                loss2 = criterion2(local_count, d)
                loss = (1-lamda)*loss1+lamda*loss2
            else:
                # Sliding window mode: only use density loss
                loss = loss1
            if seg_weight > 0 and (seg_logits is not None) and (mask is not None) and (bce_loss is not None):
                mask = mask.cuda()
                if seg_logits.size()[-2:] != mask.size()[-2:]:
                    mask_ds = F.interpolate(mask, size=seg_logits.size()[-2:], mode='nearest')
                else:
                    mask_ds = mask
                loss_seg = bce_loss(seg_logits, mask_ds)
                loss = loss + seg_weight * loss_seg
            running_loss += loss.item()
            output = output.squeeze().cpu().detach().numpy()
            output = np.clip(output,0,None) # eliminate < 0 values
            # no overall counts; only per-plot metrics

            if eval_with_mask and (seg_logits is not None) and (mask is not None):
                # predicted mask via sigmoid>0.5 over seg_logits
                pred_mask = torch.sigmoid(seg_logits)
                pred_mask = (pred_mask > 0.5).float()
                pred_mask = pred_mask.squeeze(0).squeeze(0).cpu().numpy()
                if pred_mask.shape != output.shape:
                    pred_mask = cv.resize(pred_mask.astype(np.uint8), (output.shape[1], output.shape[0]), interpolation=cv.INTER_NEAREST).astype(np.float32)
                # no overall masked counts; only IoU/Dice and per-plot metrics
                # compute IoU/Dice vs GT mask (need GT mask at output size)
                gt_mask = mask.squeeze(0).squeeze(0).cpu().numpy()
                if gt_mask.shape != output.shape:
                    gt_mask = cv.resize(gt_mask.astype(np.uint8), (output.shape[1], output.shape[0]), interpolation=cv.INTER_NEAREST).astype(np.float32)
                iou, dice = compute_iou_and_dice(pred_mask, gt_mask)
                iou_list.append(iou)
                dice_list.append(dice)

                # plot-level metrics: pred→GT many-to-one matching + per-region counting
                pd_counts_plots, gt_counts_plots = extract_matched_plot_counts(
                    output, gt_mask, pred_mask, pts,
                )
                all_pd_counts.extend(pd_counts_plots)
                all_gt_counts.extend(gt_counts_plots)
            
            # Clear CUDA cache after each image to reduce fragmentation
            torch.cuda.empty_cache()

    # 基于所有地块作为独立样本计算指标
    if len(all_pd_counts) > 0:
        mae = compute_mae(all_pd_counts, all_gt_counts)
        rmse = compute_rmse(all_pd_counts, all_gt_counts)
        # 计算 R²（所有地块作为样本，更稳定）
        if len(all_pd_counts) >= 2:
            try:
                r2 = rsquared(all_pd_counts, all_gt_counts)
            except Exception:
                r2 = 0.0
        else:
            r2 = 0.0
    else:
        mae, rmse, r2 = 0.0, 0.0, 0.0
    mean_iou = float(np.mean(iou_list)) if len(iou_list) > 0 else 0.0
    mean_dice = float(np.mean(dice_list)) if len(dice_list) > 0 else 0.0

    msg = 'epoch: {0}, mae: {1:.2f}, rmse: {2:.2f}, r2: {3:.4f}, plots: {4}'.format(
        epoch, mae, rmse, r2, len(all_pd_counts))
    msg += f', IoU: {mean_iou:.4f}, Dice: {mean_dice:.4f}'
    print(msg)

    # save stats
    net.val_loss['running_loss'].append(running_loss/(i+1))
    net.val_loss['epoch_loss'].append(mae)
    
    # stash on net for quick viewing
    if 'iou' not in net.measure:
        net.measure['iou'] = []
        net.measure['dice'] = []
    net.measure['iou'].append(mean_iou)
    net.measure['dice'].append(mean_dice)
    
    if 'plots_mae' not in net.measure:
        net.measure['plots_mae'] = []
        net.measure['plots_rmse'] = []
        net.measure['plots_r2'] = []
    net.measure['plots_mae'].append(mae)
    net.measure['plots_rmse'].append(rmse)
    net.measure['plots_r2'].append(r2)
    return [], []


def main(lamda, seg_weight=0.0, eval_with_mask=True, use_seg_guidance=True):
    ## random seed
    if torch.cuda.is_available():
        torch.cuda.manual_seed(30)
    torch.manual_seed(30)
    np.random.seed(30)

    # data preprocessing
    train_transforms = transforms.Compose([
        BBRandomCrop(crop_size, crop_num),
        BBRandomFlip(),
        BBNormalize(scale=image_scale, std=image_std, mean=image_mean, train=True),
        BBToTensor(train=True),
        BBZeroPadding(output_stride, train=True)
    ])
    val_transforms = transforms.Compose([
        BBNormalize(scale=image_scale, std=image_std, mean=image_mean, train=False),
        BBToTensor(train=False),
        BBZeroPadding(output_stride, train=False)
    ])
    trainset = BlueberryDataset(
        data_dir="dataset_blueberry_augmented",
        data_list="train.txt",
        train=True,
        transform=train_transforms
    )
    train_loader = DataLoader(
        trainset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=12,
        pin_memory=True,
        drop_last=True
    )
    valset = BlueberryDataset(
        data_dir="dataset_blueberry_augmented",
        data_list="test.txt",
        train=False,
        transform=val_transforms
    )
    val_loader = DataLoader(
        valset,
        batch_size=1,
        shuffle=False,
        num_workers=12,
        pin_memory=True  # Disabled to avoid OOM on large images
    )

    # Initiate network with seg-logits guidance option
    net = IntegrateNet(use_seg_guidance=use_seg_guidance)
    # net = nn.DataParallel(net)
    net = net.cuda()
    criterion = nn.MSELoss().cuda()
    criterion2 = nn.L1Loss().cuda()
    bce_loss = nn.BCEWithLogitsLoss().cuda() if seg_weight > 0 else None

    # Calculate and print model parameters
    trainable_params = sum(p.numel() for p in net.parameters() if p.requires_grad)
    trainable_params_m = trainable_params / 1e6  # Convert to millions
    print("="*60)
    print(f"Model: IntegrateNet with Seg-Logits Guidance")
    print(f"Use seg-logits guidance: {use_seg_guidance}")
    print(f"Trainable parameters: {trainable_params_m:.2f} M")
    print("="*60)

    # restore parameters
    net.train_loss = {'running_loss': [], 'epoch_loss': []}
    net.val_loss = {'running_loss': [], 'epoch_loss': []}
    net.measure = {'plots_mae': [], 'plots_rmse': [], 'plots_r2': []}

    # define optimizer SGD
    learning_params = [p[1] for p in net.named_parameters()]
    pretrained_params = []
    optimizer = torch.optim.SGD(
        [
            {'params': learning_params},
            {'params': pretrained_params, 'lr': learning_rate / mult},
        ],
        lr=learning_rate,
        momentum=momentum,
        weight_decay=weight_decay
    )
    # optimizer = optim.Adam(net.parameters(), lr=learning_rate)

    best_mae = 100000
    best_rmse = 0
    best_r2 = 0

    # milestones=[200,500]
    # start_epoch = 0
    # resume_epoch = -1 if start_epoch == 0 else start_epoch
    # scheduler = MultiStepLR(optimizer, milestones=milestones, gamma=0.1, last_epoch=resume_epoch)
    for epoch in range(num_epoch):
        print("epoch", epoch)
        train(net, train_loader, optimizer, criterion, criterion2, epoch, lamda, seg_weight=seg_weight, bce_loss=bce_loss)
        _, _ = validate(net, val_loader, epoch, criterion, criterion2, lamda, seg_weight=seg_weight, bce_loss=bce_loss, eval_with_mask=eval_with_mask)

        # save model parameters
        state = {
            'state_dict': net.state_dict(),
            'optimizer': optimizer.state_dict(),
            'epoch': epoch + 1,
            'train_loss': net.train_loss,
            'val_loss': net.val_loss,
            'measure': net.measure
        }

        # save model parameters each 100 epochs
        if epoch % 100 == 99:
            save_checkpoint(state,"results/models/IntegrateNet_SegLogitsGuidance", filename='model_ckpt'+str(epoch)+'.pth.tar')

        # save best model parameters and results
        if net.measure['plots_mae'][-1] <= best_mae:
            save_checkpoint(state, "results/models/IntegrateNet_SegLogitsGuidance", filename='model_best.pth')

            best_mae = net.measure['plots_mae'][-1]
            best_rmse = net.measure['plots_rmse'][-1]
            best_r2 = net.measure['plots_r2'][-1]
            best_iou = net.measure['iou'][-1]
            best_dice = net.measure['dice'][-1]
            
        # scheduler.step()

    fig = plt.figure(figsize=(16, 9))
    ax1 = fig.add_subplot(2, 2, 1)
    ax1.plot(net.train_loss['epoch_loss'], label='train loss', color='tab:blue')
    ax1.plot(net.val_loss['running_loss'], label='val loss', color='tab:red')
    ax1.legend(loc='upper right')
    ax2 = fig.add_subplot(2, 2, 2)
    ax2.plot(net.val_loss['epoch_loss'], label='val mae', color='tab:orange')
    ax2.legend(loc='upper right')
    ax3 = fig.add_subplot(2, 2, 3)
    ax3.plot(net.measure['plots_rmse'], label='val rmse', color='tab:red')
    ax3.legend(loc='upper right')
    ax4 = fig.add_subplot(2, 2, 4)
    ax4.plot(net.measure['plots_r2'], label='val r2', color='tab:red')
    ax4.legend(loc='upper right')
    plt.show()

    # plt.scatter(best_gtcounts, best_pdcounts)
    # plt.plot(best_gtcounts, best_gtcounts)
    # plt.xlabel("predicted count of crops", fontsize=15)
    # plt.ylabel("ground truth count of crops", fontsize=15)
    # plt.xticks(fontsize=15)
    # plt.yticks(fontsize=16)
    # plt.show()

    idx = net.measure['plots_mae'].index(min(net.measure['plots_mae']))
    print('lambda', lamda)
    print("the best result is: mae:", best_mae, 'rmse', best_rmse, 'r2', best_r2, 'IoU', best_iou, 'Dice', best_dice, "epoch", idx)


if __name__ == "__main__":
    # seg_weight controls L_seg; set >0 to enable segmentation supervision
    # use_seg_guidance=True: use seg_logits to guide counting features
    main(lamda=0.5, seg_weight=1.0, eval_with_mask=True, use_seg_guidance=True)

